"""Declarative base and the column mixins shared by every persistence model.

The conventions here implement the *Conventions* section of
docs/database/schema.md: `uuid` primary keys, timezone-aware UTC `timestamptz`
audit columns, and durable records carrying `created_at`/`updated_at`.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint and index names. Without this, PostgreSQL invents
# names for unnamed constraints and Alembic cannot reliably drop them again, so
# a downgrade silently fails on a database it did not create itself.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base owning the metadata Alembic compares against."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UuidPrimaryKeyMixin:
    """A `uuid` primary key generated by the application, not the database.

    Generating the value in Python means an entity carries its identity before
    it is flushed, which keeps object graphs assemblable in one unit of work and
    keeps identity generation substitutable later without a schema change.
    """

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


class CreatedAtMixin:
    """A creation timestamp for records that are written once."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class TimestampMixin(CreatedAtMixin):
    """Creation and update timestamps for durable, mutable records.

    ``onupdate`` is applied by SQLAlchemy when it emits an UPDATE. A statement
    issued outside the ORM -- a manual fix or a data migration -- must set
    ``updated_at`` itself; no database trigger enforces it.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
