"""The practice-question use case (QZ-008 to QZ-010).

Run against fakes, so what is asserted is the rule rather than the query. The
database counterparts are tests/integration/test_assessment_migration.py and
tests/integration/test_checkpoint_practice_api.py.

Three product rules are asserted repeatedly because the feature rests on them:
every question is the **learner's own** and nothing is generated or shipped, a
question is corrected **only while no quiz has asked it** — once one has, it is
retired and rewritten — and writing one **moves nothing else**.
"""

import uuid

import pytest

from app.application.dto.checkpoint_practice import (
    CURATED,
    NewQuiz,
    QuestionChanges,
    QuestionContent,
    QuestionFilters,
)
from app.application.use_cases.local_learner import AmbiguousLocalLearnerError
from app.application.use_cases.manage_practice_questions import (
    DuplicateOptionError,
    DuplicateTopicLinkError,
    EmptyQuestionUpdateError,
    LearnerNotSetUpError,
    MissingPromptError,
    MissingTopicLinkError,
    QuestionAlreadyAskedError,
    QuestionNotFoundError,
    RetiredQuestionEditError,
    TooManyTopicLinksError,
    UnknownExpectedAnswerError,
    UnknownQuestionStatusError,
    UnknownTopicError,
    UnusableOptionsError,
)
from tests.unit.fake_learner_repository import FakeLearnerRepository, learner
from tests.unit.practice_fixtures import Practising, a_question


@pytest.fixture
def practising() -> Practising:
    return Practising()


# -- writing ------------------------------------------------------------------


def test_a_written_question_keeps_what_the_learner_typed(practising):
    written = practising.author().write(a_question(topic_ids=(practising.topic.id,)))

    assert written.prompt == "How many bits address 1 KiB?"
    assert [option.text for option in written.options] == ["8", "10", "16", "1024"]
    assert written.explanation == "1 KiB is 2^10 bytes, so ten bits address it."


def test_option_keys_are_assigned_by_position(practising):
    written = practising.author().write(a_question(topic_ids=(practising.topic.id,)))

    assert [option.key for option in written.options] == ["a", "b", "c", "d"]
    assert written.expected_option_key == "b"


def test_every_question_is_the_learners_own_curated_material(practising):
    """Nothing is generated by a model or taken from a previous-year paper."""
    written = practising.author().write(a_question(topic_ids=(practising.topic.id,)))

    assert written.source_type == CURATED
    assert written.author_learner_id == practising.learner.id


def test_a_question_is_written_ready_to_ask(practising):
    written = practising.author().write(a_question(topic_ids=(practising.topic.id,)))

    assert written.status == "ready"


def test_a_question_names_the_topics_it_covers(practising):
    written = practising.author().write(a_question(topic_ids=(practising.topic.id,)))

    assert [topic.name for topic in written.topics] == ["CPU scheduling"]


def test_a_question_may_cover_a_topic_that_only_groups_subtopics(practising):
    """Where QZ-008 follows RES-001 rather than PRG-004."""
    written = practising.author().write(a_question(topic_ids=(practising.heading.id,)))

    assert [topic.name for topic in written.topics] == ["Operating Systems"]


def test_writing_moves_nothing_else(practising):
    """No quiz, no attempt, and nothing that claims a topic is understood."""
    practising.author().write(a_question(topic_ids=(practising.topic.id,)))

    assert practising.practice.quizzes == []
    assert practising.practice.attempts == []


def test_a_question_with_no_prompt_is_refused(practising):
    with pytest.raises(MissingPromptError):
        practising.author().write(a_question(prompt="   ", topic_ids=(practising.topic.id,)))


def test_a_question_offering_one_option_is_refused(practising):
    """One option is not a choice: everyone would be marked correct."""
    with pytest.raises(UnusableOptionsError):
        practising.author().write(
            a_question(
                option_texts=("10",), correct_option_index=0, topic_ids=(practising.topic.id,)
            )
        )


def test_a_blank_option_is_refused(practising):
    with pytest.raises(UnusableOptionsError):
        practising.author().write(
            a_question(option_texts=("8", "  "), topic_ids=(practising.topic.id,))
        )


def test_two_options_saying_the_same_thing_are_refused(practising):
    """A learner choosing the other one would be marked wrong for the same answer."""
    with pytest.raises(DuplicateOptionError):
        practising.author().write(
            a_question(option_texts=("10", "10"), topic_ids=(practising.topic.id,))
        )


def test_an_expected_answer_naming_no_option_is_refused(practising):
    with pytest.raises(UnknownExpectedAnswerError):
        practising.author().write(
            a_question(correct_option_index=9, topic_ids=(practising.topic.id,))
        )


def test_a_question_covering_no_topic_is_refused(practising):
    """No quiz could ever ask it: a quiz is assembled by topic."""
    with pytest.raises(MissingTopicLinkError):
        practising.author().write(a_question(topic_ids=()))


def test_a_topic_that_is_not_stored_is_refused(practising):
    with pytest.raises(UnknownTopicError):
        practising.author().write(a_question(topic_ids=(uuid.uuid4(),)))


def test_the_same_topic_named_twice_is_refused(practising):
    with pytest.raises(DuplicateTopicLinkError):
        practising.author().write(a_question(topic_ids=(practising.topic.id, practising.topic.id)))


def test_more_topics_than_one_request_may_link_is_refused(practising):
    with pytest.raises(TooManyTopicLinksError):
        practising.author().write(a_question(topic_ids=tuple(uuid.uuid4() for _ in range(101))))


def test_writing_without_a_learner_is_refused(practising):
    practising.learners = FakeLearnerRepository(())

    with pytest.raises(LearnerNotSetUpError):
        practising.author().write(a_question(topic_ids=(practising.topic.id,)))


def test_writing_with_more_than_one_learner_stored_is_refused(practising):
    practising.learners = FakeLearnerRepository((learner(), learner()))

    with pytest.raises(AmbiguousLocalLearnerError):
        practising.author().write(a_question(topic_ids=(practising.topic.id,)))


# -- listing ------------------------------------------------------------------


def test_questions_are_listed_newest_first(practising):
    author = practising.author()
    author.write(a_question(prompt="First", topic_ids=(practising.topic.id,)))
    author.write(a_question(prompt="Second", topic_ids=(practising.topic.id,)))

    page = author.list_questions(filters=QuestionFilters(), limit=25, offset=0)

    assert [question.prompt for question in page.questions] == ["Second", "First"]
    assert page.total == 2


def test_a_topic_filter_narrows_to_that_topic(practising):
    author = practising.author()
    author.write(a_question(prompt="Scheduling", topic_ids=(practising.topic.id,)))
    author.write(a_question(prompt="Paging", topic_ids=(practising.other_topic.id,)))

    page = author.list_questions(
        filters=QuestionFilters(topic_id=practising.other_topic.id), limit=25, offset=0
    )

    assert [question.prompt for question in page.questions] == ["Paging"]


def test_a_topic_matching_nothing_is_an_empty_page_rather_than_a_failure(practising):
    page = practising.author().list_questions(
        filters=QuestionFilters(topic_id=uuid.uuid4()), limit=25, offset=0
    )

    assert page.questions == ()
    assert page.total == 0


def test_an_unknown_status_filter_is_refused(practising):
    """A caller asking for one has misread the contract; an empty page would hide it."""
    with pytest.raises(UnknownQuestionStatusError):
        practising.author().list_questions(
            filters=QuestionFilters(status="draft"), limit=25, offset=0
        )


def test_an_installation_with_no_learner_lists_nothing(practising):
    practising.learners = FakeLearnerRepository(())

    page = practising.author().list_questions(filters=QuestionFilters(), limit=25, offset=0)

    assert page.questions == ()
    assert page.total == 0


# -- retiring -----------------------------------------------------------------


def test_a_question_can_be_retired(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    retired = author.update(written.id, QuestionChanges(status="retired"))

    assert retired.status == "retired"


def test_retiring_is_reversible(practising):
    """Nothing here deletes a question: attempts reference it."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    author.update(written.id, QuestionChanges(status="retired"))

    restored = author.update(written.id, QuestionChanges(status="ready"))

    assert restored.status == "ready"
    assert len(practising.practice.questions) == 1


def test_retiring_keeps_everything_the_question_said(practising):
    """A status-only update moves the status and nothing else."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    retired = author.update(written.id, QuestionChanges(status="retired"))

    assert retired.prompt == written.prompt
    assert retired.options == written.options
    assert retired.expected_option_key == written.expected_option_key
    assert retired.explanation == written.explanation
    assert retired.written_at == written.written_at


def test_an_update_naming_no_field_is_refused(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(EmptyQuestionUpdateError):
        author.update(written.id, QuestionChanges())


def test_a_status_a_learner_may_not_ask_for_is_refused(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(UnknownQuestionStatusError):
        author.update(written.id, QuestionChanges(status="draft"))


def test_a_question_that_is_not_stored_is_reported_as_missing(practising):
    with pytest.raises(QuestionNotFoundError):
        practising.author().update(uuid.uuid4(), QuestionChanges(status="retired"))


def test_another_learners_question_is_reported_as_missing(practising):
    """Saying "that exists but is not yours" would confirm a record they may not read."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    practising.learners = FakeLearnerRepository((learner(),))

    with pytest.raises(QuestionNotFoundError):
        practising.author().update(written.id, QuestionChanges(status="retired"))


# -- correcting ---------------------------------------------------------------


def a_correction(**fields: object) -> QuestionContent:
    """A whole replacement content group, overridable field by field."""
    defaults: dict[str, object] = {
        "prompt": "How many bits address 1 MiB?",
        "option_texts": ("10", "20", "16"),
        "correct_option_index": 1,
        "explanation": "1 MiB is 2^20 bytes, so twenty bits address it.",
        "topic_ids": (),
    }
    defaults.update(fields)
    return QuestionContent(**defaults)  # type: ignore[arg-type]


def test_a_question_no_quiz_has_asked_can_be_corrected(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
    )

    assert corrected.prompt == "How many bits address 1 MiB?"
    assert [option.text for option in corrected.options] == ["10", "20", "16"]
    assert corrected.explanation == "1 MiB is 2^20 bytes, so twenty bits address it."


def test_correcting_keeps_the_question_and_its_identity(practising):
    """A correction is the same question said better, not a second one."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
    )

    assert corrected.id == written.id
    assert len(practising.practice.questions) == 1


def test_correcting_leaves_written_at_alone(practising):
    """`written_at` orders a quiz, so moving it would reorder one."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
    )

    assert corrected.written_at == written.written_at


def test_option_keys_are_reassigned_by_position_on_a_correction(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
    )

    assert [option.key for option in corrected.options] == ["a", "b", "c"]
    assert corrected.expected_option_key == "b"


def test_a_correction_replaces_the_topics_it_covers(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.other_topic.id,)))
    )

    assert [topic.id for topic in corrected.topics] == [practising.other_topic.id]


def test_a_correction_leaving_out_an_explanation_clears_it(practising):
    """The content is one group, so a member left out is unset (ADR-019's rule)."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id,
        QuestionChanges(content=a_correction(explanation=None, topic_ids=(practising.topic.id,))),
    )

    assert corrected.explanation is None


def test_a_correction_can_travel_with_a_status(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    corrected = author.update(
        written.id,
        QuestionChanges(status="retired", content=a_correction(topic_ids=(practising.topic.id,))),
    )

    assert corrected.status == "retired"
    assert corrected.prompt == "How many bits address 1 MiB?"


def test_a_question_a_quiz_has_asked_cannot_be_corrected(practising):
    """The rule ADR-033 gave and ADR-035 narrowed: history must not be rewritten."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    practising.quizzes().assemble(NewQuiz(topic_ids=(practising.topic.id,)))

    with pytest.raises(QuestionAlreadyAskedError):
        author.update(
            written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
        )


def test_a_question_a_quiz_has_asked_can_still_be_retired(practising):
    """Setting aside stays available: it is what a learner does instead of correcting."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    practising.quizzes().assemble(NewQuiz(topic_ids=(practising.topic.id,)))

    retired = author.update(written.id, QuestionChanges(status="retired"))

    assert retired.status == "retired"


def test_a_refused_correction_changes_nothing(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    practising.quizzes().assemble(NewQuiz(topic_ids=(practising.topic.id,)))

    with pytest.raises(QuestionAlreadyAskedError):
        author.update(
            written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
        )

    assert practising.practice.questions[0].prompt == written.prompt
    assert practising.practice.questions[0].expected_option_key == written.expected_option_key


def test_a_question_set_aside_cannot_be_corrected_as_it_stands(practising):
    """ADR-032's two-step: bring it back, then correct it."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    author.update(written.id, QuestionChanges(status="retired"))

    with pytest.raises(RetiredQuestionEditError):
        author.update(
            written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
        )


def test_bringing_a_question_back_lets_it_be_corrected_again(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    author.update(written.id, QuestionChanges(status="retired"))
    author.update(written.id, QuestionChanges(status="ready"))

    corrected = author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
    )

    assert corrected.prompt == "How many bits address 1 MiB?"


def test_a_correction_asking_to_be_brought_back_at_once_is_still_refused(practising):
    """Eligibility is read from what is stored, never from the request."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))
    author.update(written.id, QuestionChanges(status="retired"))

    with pytest.raises(RetiredQuestionEditError):
        author.update(
            written.id,
            QuestionChanges(status="ready", content=a_correction(topic_ids=(practising.topic.id,))),
        )


def test_a_correction_with_no_prompt_is_refused(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(MissingPromptError):
        author.update(
            written.id,
            QuestionChanges(content=a_correction(prompt="  ", topic_ids=(practising.topic.id,))),
        )


def test_a_correction_repeating_an_option_is_refused(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(DuplicateOptionError):
        author.update(
            written.id,
            QuestionChanges(
                content=a_correction(option_texts=("10", "10"), topic_ids=(practising.topic.id,))
            ),
        )


def test_a_correction_whose_expected_answer_names_no_option_is_refused(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(UnknownExpectedAnswerError):
        author.update(
            written.id,
            QuestionChanges(
                content=a_correction(correct_option_index=9, topic_ids=(practising.topic.id,))
            ),
        )


def test_a_correction_covering_no_topic_is_refused(practising):
    """A question covering nothing could never be asked, exactly as when written."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(MissingTopicLinkError):
        author.update(written.id, QuestionChanges(content=a_correction(topic_ids=())))


def test_a_correction_naming_a_topic_that_is_not_stored_is_refused(practising):
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    with pytest.raises(UnknownTopicError):
        author.update(written.id, QuestionChanges(content=a_correction(topic_ids=(uuid.uuid4(),))))


def test_correcting_moves_nothing_else(practising):
    """No quiz, no attempt, no stage, no plan, and no revision."""
    author = practising.author()
    written = author.write(a_question(topic_ids=(practising.topic.id,)))

    author.update(
        written.id, QuestionChanges(content=a_correction(topic_ids=(practising.topic.id,)))
    )

    assert practising.practice.quizzes == []
    assert practising.practice.attempts == []
