"""Stored PDF files against a real database and a real filesystem.

The API tests prove the contract against fakes. These prove the parts a fake
cannot: that a row and its bytes survive a round trip through PostgreSQL and a
real directory together, that the table's constraints hold, and that a genuinely
malformed PDF is refused by the real `pypdf` rather than by a stub.

**Files are written under `tmp_path`, never the configured volume**, so a test
run leaves nothing behind and never touches a learner's material.

**Every PDF here is generated by the test.** Nothing in this repository ships a
learner's file, and nothing reads one from disk.

Skipped unless ``TEST_DATABASE_URL`` names a disposable database; see
tests/integration/conftest.py.
"""

import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from io import BytesIO
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from pypdf import PdfWriter
from sqlalchemy import Engine, func, select, text
from sqlalchemy.orm import Session

from app.application.use_cases.manage_resource_files import ManageResourceFiles
from app.application.use_cases.manage_resources import ManageResources
from app.composition.app_factory import create_app
from app.composition.config import Settings
from app.infrastructure.persistence.engine import create_database_engine, create_session_factory
from app.infrastructure.persistence.learner_repository import SqlAlchemyLearnerRepository
from app.infrastructure.persistence.resource_file_repository import (
    SqlAlchemyResourceFileRepository,
)
from app.infrastructure.persistence.resource_note_repository import (
    SqlAlchemyResourceNoteRepository,
)
from app.infrastructure.persistence.resource_repository import SqlAlchemyResourceRepository
from app.infrastructure.persistence.resources import (
    Resource,
    ResourceFile,
    ResourceNote,
    ResourceTopicLink,
)
from app.infrastructure.storage.local_file_storage import (
    LocalResourceFileStorage,
    PyPdfDocumentInspector,
)
from app.presentation.api.dependencies import RESOURCE_FILES_PROVIDER, RESOURCES_PROVIDER

LEARNER = "/api/v1/learner"
RESOURCES = "/api/v1/resources"
FILES = "/api/v1/resource-files"


def a_pdf(pages: int = 4) -> bytes:
    """A real, valid PDF the test generated."""
    writer = PdfWriter()
    for _ in range(pages):
        writer.add_blank_page(width=200, height=200)
    buffer = BytesIO()
    writer.write(buffer)
    return buffer.getvalue()


@pytest.fixture
def storage_root(tmp_path: Path) -> Path:
    """A storage root this test owns. **Never the configured volume.**"""
    return tmp_path / "resource-files"


@pytest.fixture
def client(
    migrated_database: Engine, database_url: str, storage_root: Path
) -> Iterator[TestClient]:
    """A client wired to the test database and a real directory on disk."""
    app = create_app(Settings(database_url=database_url))
    session_factory = create_session_factory(create_database_engine(database_url))
    storage = LocalResourceFileStorage(root=storage_root)

    @contextmanager
    def provide() -> Iterator[ManageResourceFiles]:
        with session_factory() as session:
            try:
                yield ManageResourceFiles(
                    learners=SqlAlchemyLearnerRepository(session),
                    resources=SqlAlchemyResourceRepository(session),
                    files=SqlAlchemyResourceFileRepository(session),
                    storage=storage,
                    inspector=PyPdfDocumentInspector(),
                )
            except BaseException:
                session.rollback()
                raise
            session.commit()

    @contextmanager
    def provide_resources() -> Iterator[ManageResources]:
        # RES-005 unlinks bytes when it removes a resource, so the catalogue must
        # hold the SAME storage root the file endpoints write to. Left on the
        # app's configured adapter, a removal would unlink from the deployment
        # path and this test's directory would keep its files.
        with session_factory() as session:
            try:
                yield ManageResources(
                    learners=SqlAlchemyLearnerRepository(session),
                    resources=SqlAlchemyResourceRepository(session),
                    notes=SqlAlchemyResourceNoteRepository(session),
                    files=SqlAlchemyResourceFileRepository(session),
                    storage=storage,
                )
            except BaseException:
                session.rollback()
                raise
            session.commit()

    setattr(app.state, RESOURCE_FILES_PROVIDER, provide)
    setattr(app.state, RESOURCES_PROVIDER, provide_resources)
    with TestClient(app) as test_client:
        yield test_client


@pytest.fixture
def learner(client: TestClient) -> dict:
    """The local learner, created through LRN-002 as the setup screen does."""
    response = client.patch(f"{LEARNER}/profile", json={"display_name": "Asha"})
    assert response.status_code == 200
    return response.json()["data"]


@pytest.fixture
def resource(client: TestClient, learner: dict) -> dict:
    """One piece of catalogued material, with no topics linked."""
    response = client.post(
        RESOURCES,
        json={
            "resource_type": "pdf",
            "title": "Operating Systems notes",
            "source_label": "Blue binder",
            "topic_ids": [],
        },
    )
    assert response.status_code == 201, response.text
    return response.json()["data"]


def upload(client: TestClient, resource_id: str, *, filename="chapter.pdf", content=None):
    return client.post(
        f"{RESOURCES}/{resource_id}/files",
        files={"file": (filename, content if content is not None else a_pdf(), "application/pdf")},
    )


# -- a row and its bytes, together -------------------------------------------


def test_a_pdf_round_trips_through_the_database_and_the_disk(
    client: TestClient, resource: dict, storage_root: Path
):
    content = a_pdf(pages=6)

    created = upload(client, resource["id"], content=content)

    assert created.status_code == 201, created.text
    data = created.json()["data"]
    # The real inspector counted the pages, not a stub.
    assert data["page_count"] == 6
    assert data["byte_size"] == len(content)

    downloaded = client.get(f"{FILES}/{data['id']}/content")
    assert downloaded.status_code == 200
    assert downloaded.content == content

    # And the bytes really are on disk, sharded, under the test's own root.
    written = list(storage_root.rglob("*.pdf"))
    assert len(written) == 1
    assert written[0].read_bytes() == content
    assert written[0].relative_to(storage_root).parts[:2] != ()


def test_the_stored_path_contains_no_part_of_the_learners_filename(
    client: TestClient, resource: dict, storage_root: Path
):
    upload(client, resource["id"], filename="Operating Systems Chapter 3.pdf")

    written = list(storage_root.rglob("*.pdf"))[0]

    assert "Operating" not in str(written)
    assert "Chapter" not in str(written)


def test_a_real_malformed_pdf_is_refused_by_the_real_parser(
    client: TestClient, resource: dict, storage_root: Path
):
    """Truncated part-way, so the signature passes and the parse does not."""
    whole = a_pdf(pages=5)

    response = upload(client, resource["id"], content=whole[: len(whole) // 3])

    assert response.status_code == 422, response.text
    assert list(storage_root.rglob("*.pdf")) == []


def an_encrypted_pdf(user_password: str, *, pages: int = 2) -> bytes:
    """A real AES-256 encrypted PDF, as publisher and scanned files are."""
    writer = PdfWriter()
    for _ in range(pages):
        writer.add_blank_page(width=200, height=200)
    writer.encrypt(user_password, algorithm="AES-256")
    buffer = BytesIO()
    writer.write(buffer)
    return buffer.getvalue()


def test_a_password_locked_pdf_is_refused(client: TestClient, resource: dict, storage_root: Path):
    response = upload(client, resource["id"], content=an_encrypted_pdf("a-password"))

    assert response.status_code == 422, response.text
    assert "password" in response.json()["error"]["message"].lower()
    assert list(storage_root.rglob("*.pdf")) == []


def test_a_restricted_pdf_with_no_password_is_stored(
    client: TestClient, resource: dict, storage_root: Path
):
    """The real-world case: encrypted, but openable, so LearnFlow keeps it.

    Before `cryptography` was added, an AES document raised from inside the
    parser and the learner met an unexplained error rather than either outcome.
    """
    content = an_encrypted_pdf("", pages=7)

    response = upload(client, resource["id"], content=content)

    assert response.status_code == 201, response.text
    assert response.json()["data"]["page_count"] == 7
    assert len(list(storage_root.rglob("*.pdf"))) == 1
    # Stored byte for byte: LearnFlow never rewrites or decrypts the file itself.
    assert list(storage_root.rglob("*.pdf"))[0].read_bytes() == content


def test_an_aes_pdf_never_produces_an_unhandled_error(client: TestClient, resource: dict):
    """The regression that showed a learner "An unexpected error occurred"."""
    for password in ("", "a-password"):
        response = upload(client, resource["id"], content=an_encrypted_pdf(password))
        assert response.status_code in {201, 422}, response.text
        assert response.status_code != 500


def test_several_files_are_stored_separately(
    client: TestClient, resource: dict, storage_root: Path
):
    upload(client, resource["id"], filename="one.pdf", content=a_pdf(pages=1))
    upload(client, resource["id"], filename="two.pdf", content=a_pdf(pages=2))

    assert len(list(storage_root.rglob("*.pdf"))) == 2
    listed = client.get(f"{RESOURCES}/{resource['id']}/files").json()["data"]
    assert {f["page_count"] for f in listed} == {1, 2}


# -- the lifecycle, against real rows ----------------------------------------


def test_archiving_a_file_leaves_its_bytes_on_disk(
    client: TestClient, resource: dict, storage_root: Path
):
    created = upload(client, resource["id"]).json()["data"]

    client.patch(f"{FILES}/{created['id']}", json={"status": "archived"})

    assert len(list(storage_root.rglob("*.pdf"))) == 1
    assert client.get(f"{FILES}/{created['id']}/content").status_code == 200


def test_a_file_survives_being_archived_and_restored(client: TestClient, resource: dict):
    content = a_pdf(pages=3)
    created = upload(client, resource["id"], content=content).json()["data"]

    client.patch(f"{FILES}/{created['id']}", json={"status": "archived"})
    restored = client.patch(f"{FILES}/{created['id']}", json={"status": "active"})

    assert restored.json()["data"]["status"] == "active"
    assert client.get(f"{FILES}/{created['id']}/content").content == content


def test_archiving_the_resource_freezes_its_files(client: TestClient, resource: dict):
    created = upload(client, resource["id"]).json()["data"]
    client.patch(f"{RESOURCES}/{resource['id']}", json={"status": "archived"})

    assert upload(client, resource["id"]).status_code == 409
    assert client.patch(f"{FILES}/{created['id']}", json={"status": "archived"}).status_code == 409
    # Still readable, and still downloadable.
    assert len(client.get(f"{RESOURCES}/{resource['id']}/files").json()["data"]) == 1
    assert client.get(f"{FILES}/{created['id']}/content").status_code == 200


def test_a_row_whose_bytes_were_removed_reports_missing_rather_than_failing(
    client: TestClient, resource: dict, storage_root: Path
):
    """What a volume restored from an older backup would look like."""
    created = upload(client, resource["id"]).json()["data"]
    for stored_file in storage_root.rglob("*.pdf"):
        stored_file.unlink()

    assert client.get(f"{FILES}/{created['id']}/content").status_code == 404
    # The row is still listed: LearnFlow does not quietly forget the record.
    assert len(client.get(f"{RESOURCES}/{resource['id']}/files").json()["data"]) == 1


# -- removing a file, and what each failure leaves behind ---------------------


def test_removing_a_file_deletes_the_row_and_the_bytes_together(
    client: TestClient, resource: dict, storage_root: Path, session: Session
):
    """RES-018 against a real database and a real directory."""
    created = upload(client, resource["id"]).json()["data"]
    assert len(list(storage_root.rglob("*.pdf"))) == 1

    removed = client.delete(f"{FILES}/{created['id']}")

    assert removed.status_code == 204, removed.text
    assert removed.content == b""
    assert list(storage_root.rglob("*.pdf")) == []
    assert session.scalar(select(func.count()).select_from(ResourceFile)) == 0


def test_removing_one_file_leaves_the_others_bytes_on_disk(
    client: TestClient, resource: dict, storage_root: Path
):
    keep = upload(client, resource["id"], filename="keep.pdf").json()["data"]
    drop = upload(client, resource["id"], filename="drop.pdf").json()["data"]

    assert client.delete(f"{FILES}/{drop['id']}").status_code == 204

    assert len(list(storage_root.rglob("*.pdf"))) == 1
    assert client.get(f"{FILES}/{keep['id']}/content").status_code == 200


def test_a_removed_file_leaves_the_listing_the_download_and_a_retry(
    client: TestClient, resource: dict
):
    created = upload(client, resource["id"]).json()["data"]

    client.delete(f"{FILES}/{created['id']}")

    assert client.get(f"{RESOURCES}/{resource['id']}/files").json()["data"] == []
    assert client.get(f"{FILES}/{created['id']}/content").status_code == 404
    # A second attempt names something that no longer exists.
    assert client.delete(f"{FILES}/{created['id']}").status_code == 404


def test_removing_a_file_leaves_its_resource_and_notes_alone(
    client: TestClient, resource: dict, session: Session
):
    """Only the file named goes. RES-005 -- removing a whole resource -- stays
    unimplemented, and nothing here approximates it."""
    created = upload(client, resource["id"]).json()["data"]
    written = client.post(
        f"{RESOURCES}/{resource['id']}/notes",
        json={"title": "Deadlock conditions", "body": "Mutual exclusion."},
    )
    assert written.status_code == 201, written.text

    client.delete(f"{FILES}/{created['id']}")

    assert client.get(f"{RESOURCES}/{resource['id']}").status_code == 200
    assert session.scalar(select(func.count()).select_from(Resource)) == 1
    assert session.scalar(select(func.count()).select_from(ResourceNote)) == 1


def test_the_empty_shard_directories_are_left_behind(
    client: TestClient, resource: dict, storage_root: Path
):
    """Pruning is how a delete routine grows into one that removes more than it
    was asked to. An empty shard costs nothing."""
    created = upload(client, resource["id"]).json()["data"]
    shards = {path for path in storage_root.rglob("*") if path.is_dir()}
    assert shards

    client.delete(f"{FILES}/{created['id']}")

    assert {path for path in storage_root.rglob("*") if path.is_dir()} == shards


def test_a_file_whose_bytes_are_already_gone_can_still_be_removed(
    client: TestClient, resource: dict, storage_root: Path, session: Session
):
    """What a commit failing after an unlink would leave. Asking again clears the
    row instead of reporting a fault."""
    created = upload(client, resource["id"]).json()["data"]
    for stored_file in storage_root.rglob("*.pdf"):
        stored_file.unlink()

    assert client.delete(f"{FILES}/{created['id']}").status_code == 204
    assert session.scalar(select(func.count()).select_from(ResourceFile)) == 0


def test_a_failed_unlink_deletes_nothing_at_all(
    client: TestClient,
    resource: dict,
    storage_root: Path,
    session: Session,
    monkeypatch: pytest.MonkeyPatch,
):
    """The row deletion is uncommitted when the bytes are unlinked, so an unlink
    that raises takes the row deletion down with it and the learner keeps their
    file. This is the failure `ManageResourceFiles.delete_file` documents."""
    created = upload(client, resource["id"]).json()["data"]

    def refuse(self: LocalResourceFileStorage, storage_key: str) -> None:
        raise OSError("read-only file system")

    monkeypatch.setattr(LocalResourceFileStorage, "remove", refuse)

    with pytest.raises(OSError):
        client.delete(f"{FILES}/{created['id']}")

    session.rollback()
    assert session.scalar(select(func.count()).select_from(ResourceFile)) == 1
    assert len(list(storage_root.rglob("*.pdf"))) == 1


# -- removing the whole resource (RES-005) ------------------------------------


def test_removing_a_resource_deletes_its_rows_and_its_bytes(
    client: TestClient, resource: dict, storage_root: Path, session: Session
):
    """RES-005 against a real database and a real directory.

    The strongest evidence this feature works: real rows in PostgreSQL and real
    files on disk, both gone, with no cascade in the schema doing it.
    """
    upload(client, resource["id"], filename="a.pdf")
    upload(client, resource["id"], filename="b.pdf")
    written = client.post(
        f"{RESOURCES}/{resource['id']}/notes",
        json={"title": "Deadlock conditions", "body": "Mutual exclusion."},
    )
    assert written.status_code == 201, written.text
    assert len(list(storage_root.rglob("*.pdf"))) == 2

    removed = client.delete(f"{RESOURCES}/{resource['id']}")

    assert removed.status_code == 204, removed.text
    assert removed.content == b""
    # The bytes are gone from the real directory.
    assert list(storage_root.rglob("*.pdf")) == []
    # Every owned row is gone, and so is the resource.
    assert session.scalar(select(func.count()).select_from(ResourceFile)) == 0
    assert session.scalar(select(func.count()).select_from(ResourceNote)) == 0
    assert session.scalar(select(func.count()).select_from(ResourceTopicLink)) == 0
    assert session.scalar(select(func.count()).select_from(Resource)) == 0


def test_the_foreign_keys_are_still_not_cascades(
    client: TestClient, resource: dict, session: Session
):
    """The use case clears children itself. If it ever stops, the constraint is
    what fails loudly rather than letting a delete widen silently."""
    upload(client, resource["id"])

    with pytest.raises(Exception):  # noqa: B017 - any IntegrityError shape will do
        session.execute(text("DELETE FROM resources WHERE id = :id"), {"id": resource["id"]})
        session.commit()
    session.rollback()


def test_removing_one_resource_leaves_another_resources_rows_and_bytes(
    client: TestClient, resource: dict, storage_root: Path, session: Session
):
    other = client.post(
        RESOURCES,
        json={
            "resource_type": "pdf",
            "title": "Keep this",
            "source_label": "Green binder",
            "topic_ids": [],
        },
    )
    assert other.status_code == 201, other.text
    keep = other.json()["data"]
    upload(client, keep["id"], filename="keep.pdf")
    upload(client, resource["id"], filename="drop.pdf")

    assert client.delete(f"{RESOURCES}/{resource['id']}").status_code == 204

    assert len(list(storage_root.rglob("*.pdf"))) == 1
    assert session.scalar(select(func.count()).select_from(Resource)) == 1
    assert len(client.get(f"{RESOURCES}/{keep['id']}/files").json()["data"]) == 1


def test_the_empty_shard_directories_survive_a_resource_removal(
    client: TestClient, resource: dict, storage_root: Path
):
    """Pruning is how a delete routine grows into one that removes more than it
    was asked to."""
    upload(client, resource["id"])
    shards = {path for path in storage_root.rglob("*") if path.is_dir()}
    assert shards

    client.delete(f"{RESOURCES}/{resource['id']}")

    assert {path for path in storage_root.rglob("*") if path.is_dir()} == shards


def test_a_failed_unlink_removes_no_row_and_no_byte(
    client: TestClient,
    resource: dict,
    storage_root: Path,
    session: Session,
    monkeypatch: pytest.MonkeyPatch,
):
    """Every row deletion is uncommitted while the bytes are unlinked, so one
    failed unlink rolls the whole removal back and the learner keeps everything.
    """
    upload(client, resource["id"], filename="a.pdf")
    upload(client, resource["id"], filename="b.pdf")

    def refuse(self: LocalResourceFileStorage, storage_key: str) -> None:
        raise OSError("read-only file system")

    monkeypatch.setattr(LocalResourceFileStorage, "remove", refuse)

    with pytest.raises(OSError):
        client.delete(f"{RESOURCES}/{resource['id']}")

    session.rollback()
    assert session.scalar(select(func.count()).select_from(Resource)) == 1
    assert session.scalar(select(func.count()).select_from(ResourceFile)) == 2
    assert len(list(storage_root.rglob("*.pdf"))) == 2


# -- what the table itself enforces ------------------------------------------


def test_the_table_refuses_an_unknown_status(client: TestClient, resource: dict, session: Session):
    created = upload(client, resource["id"]).json()["data"]

    with pytest.raises(Exception):  # noqa: B017 - any IntegrityError shape will do
        session.execute(
            text("UPDATE resource_files SET status = 'deleted' WHERE id = :id"),
            {"id": created["id"]},
        )
        session.commit()
    session.rollback()


def test_the_table_refuses_an_empty_storage_key(
    client: TestClient, resource: dict, session: Session
):
    created = upload(client, resource["id"]).json()["data"]

    with pytest.raises(Exception):  # noqa: B017
        session.execute(
            text("UPDATE resource_files SET storage_key = '   ' WHERE id = :id"),
            {"id": created["id"]},
        )
        session.commit()
    session.rollback()


def test_a_file_row_cannot_name_a_resource_that_does_not_exist(session: Session):
    with pytest.raises(Exception):  # noqa: B017
        session.execute(
            text(
                "INSERT INTO resource_files "
                "(id, resource_id, storage_key, original_filename, byte_size, "
                " page_count, content_type, checksum, status) "
                "VALUES (:id, :resource, 'ab/cd/x.pdf', 'a.pdf', 1, 1, "
                "'application/pdf', 'x', 'active')"
            ),
            {"id": uuid.uuid4(), "resource": uuid.uuid4()},
        )
        session.commit()
    session.rollback()


def test_nothing_derived_is_stored_alongside_a_file(session: Session):
    """No extracted text, no chunk, no embedding — and no ingestion table."""
    columns = {
        row[0]
        for row in session.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = 'resource_files'"
            )
        )
    }
    assert columns == {
        "id",
        "resource_id",
        "storage_key",
        "original_filename",
        "byte_size",
        "page_count",
        "content_type",
        "checksum",
        "status",
        "created_at",
        "updated_at",
    }

    tables = {
        row[0]
        for row in session.execute(
            text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")
        )
    }
    assert "resource_ingestions" not in tables


def test_the_approved_single_file_columns_stay_uncreated(session: Session):
    """`resources.storage_key` and `resources.metadata` are deliberately absent.

    They describe **one** file per resource, which is not the shape a learner
    with several PDFs needs, so `resource_files` holds them instead.
    """
    columns = {
        row[0]
        for row in session.execute(
            text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = 'resources'"
            )
        )
    }
    assert "storage_key" not in columns
    assert "metadata" not in columns
