"""Practice-question endpoints (QZ-008 to QZ-010).

They hold the question bank the checkpoint quizzes in `checkpoint_quizzes` are
assembled from, and together they serve **FR-009 — Topic Checkpoint Practice**.

**The learner writes every question.** Nothing is generated by a model, taken
from a previous-year paper, scraped, or shipped with the repository, so no
third-party question content and no licensing question enters LearnFlow. See
ADR-033.

Every route here is thin: validate, call the use case, map the result or its
error to a documented response. No route touches a session, a model, or a query
(docs/architecture/dependency-rules.md).

No route accepts a learner identifier. The effective learner is resolved
server-side, so a request cannot read or change another learner's questions
(docs/api/conventions.md).
"""

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query
from starlette.status import (
    HTTP_201_CREATED,
    HTTP_404_NOT_FOUND,
    HTTP_409_CONFLICT,
    HTTP_422_UNPROCESSABLE_CONTENT,
)

from app.application.dto.checkpoint_practice import QUESTION_STATUSES, QuestionFilters
from app.application.use_cases.local_learner import AmbiguousLocalLearnerError
from app.application.use_cases.manage_practice_questions import (
    DuplicateOptionError,
    DuplicateTopicLinkError,
    EmptyQuestionUpdateError,
    LearnerNotSetUpError,
    ManagePracticeQuestions,
    MissingPromptError,
    MissingTopicLinkError,
    QuestionNotFoundError,
    TooManyTopicLinksError,
    UnknownExpectedAnswerError,
    UnknownQuestionStatusError,
    UnknownTopicError,
    UnusableOptionsError,
)
from app.presentation.api import API_V1_PREFIX
from app.presentation.api.dependencies import provide_practice_questions
from app.presentation.api.errors import ErrorDetail, ErrorResponse, RequestRejected
from app.presentation.api.schemas.checkpoint_practice import (
    QuestionCollectionResponse,
    QuestionResponse,
    QuestionSchema,
    UpdateQuestionRequest,
    WriteQuestionRequest,
)
from app.presentation.api.schemas.pagination import DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE

router = APIRouter(prefix=f"{API_V1_PREFIX}/practice-questions", tags=["checkpoint practice"])

_NOT_FOUND_RESPONSE = {HTTP_404_NOT_FOUND: {"model": ErrorResponse}}
_CONFLICT_RESPONSE = {HTTP_409_CONFLICT: {"model": ErrorResponse}}

Author = Annotated[ManagePracticeQuestions, Depends(provide_practice_questions)]


def _rejected(field: str, message: str, rule: str) -> RequestRejected:
    """One field-level rejection, in the documented error envelope.

    The rejected value is never echoed back, per docs/api/conventions.md.
    """
    return RequestRejected(
        status_code=HTTP_422_UNPROCESSABLE_CONTENT,
        detail=message,
        details=[ErrorDetail(field=field, message=message, type=rule)],
    )


@router.post(
    "",
    summary="Write one practice question against the topics it covers",
    response_model=QuestionResponse,
    status_code=HTTP_201_CREATED,
    responses=_CONFLICT_RESPONSE,
)
def write_question(request: WriteQuestionRequest, author: Author) -> QuestionResponse:
    """Record one multiple-choice question the learner has written.

    Option keys are assigned by LearnFlow from each option's position — the first
    is `a`, the second `b` — so a stored expected answer always names an option
    the question offers.

    A question may cover **any** stored topic, including one that only groups
    subtopics, which follows RES-001 rather than PRG-004: a question about a whole
    heading is ordinary, while a *stage* claiming understanding of one is not.

    Nothing else moves: no learning stage, no plan, no plan item, and no revision.

    QZ-008. Serves FR-009.
    """
    try:
        question = author.write(request.to_new_question())
    except MissingPromptError as error:
        raise _rejected("body.prompt", str(error), "missing_prompt") from error
    except DuplicateOptionError as error:
        raise _rejected("body.options", str(error), "duplicate_option") from error
    except UnusableOptionsError as error:
        raise _rejected("body.options", str(error), "unusable_options") from error
    except UnknownExpectedAnswerError as error:
        raise _rejected(
            "body.correct_option_index", str(error), "unknown_expected_answer"
        ) from error
    except MissingTopicLinkError as error:
        raise _rejected("body.topic_ids", str(error), "missing_topic") from error
    except UnknownTopicError as error:
        raise _rejected("body.topic_ids", str(error), "unknown_topic") from error
    except DuplicateTopicLinkError as error:
        raise _rejected("body.topic_ids", str(error), "duplicate_topic") from error
    except TooManyTopicLinksError as error:
        raise _rejected("body.topic_ids", str(error), "too_many_topics") from error
    except (LearnerNotSetUpError, AmbiguousLocalLearnerError) as error:
        raise HTTPException(status_code=HTTP_409_CONFLICT, detail=str(error)) from error
    return QuestionResponse(data=QuestionSchema.of(question))


@router.get(
    "",
    summary="List the practice questions the learner has written",
    response_model=QuestionCollectionResponse,
    responses=_CONFLICT_RESPONSE,
)
def list_questions(
    author: Author,
    topic_id: Annotated[
        uuid.UUID | None, Query(description="Only questions covering this topic.")
    ] = None,
    status: Annotated[
        str | None, Query(description=f"One of: {', '.join(QUESTION_STATUSES)}.")
    ] = None,
    limit: Annotated[
        int, Query(ge=1, le=MAX_PAGE_SIZE, description="Maximum number of questions to return.")
    ] = DEFAULT_PAGE_SIZE,
    offset: Annotated[int, Query(ge=0, description="Number of questions to skip.")] = 0,
) -> QuestionCollectionResponse:
    """Read the local learner's practice questions, newest first.

    **This response carries the expected answers**, because it is the author
    reading back what they wrote. A quiz being taken reads QZ-002 instead, which
    has nowhere to put one.

    **No status is assumed.** A caller wanting only what a quiz may ask asks for
    `ready`, and one wanting what has been set aside asks for `retired`, which is
    how PLN-002, REV-001, and RES-002 treat their own statuses.

    An installation where setup has not run has no learner and therefore no
    questions, which is an empty page rather than a failure. A `topic_id` matching
    nothing is an empty page too; an unknown *status* is a `422`, because a caller
    asking for one has misread the contract.

    QZ-009. Serves FR-009.
    """
    try:
        page = author.list_questions(
            filters=QuestionFilters(topic_id=topic_id, status=status),
            limit=limit,
            offset=offset,
        )
    except UnknownQuestionStatusError as error:
        raise _rejected("query.status", str(error), "unknown_question_status") from error
    except AmbiguousLocalLearnerError as error:
        raise HTTPException(status_code=HTTP_409_CONFLICT, detail=str(error)) from error
    return QuestionCollectionResponse.of(page, limit=limit, offset=offset)


@router.patch(
    "/{question_id}",
    summary="Set a practice question aside, or bring it back",
    response_model=QuestionResponse,
    responses=_NOT_FOUND_RESPONSE | _CONFLICT_RESPONSE,
)
def update_question(
    question_id: uuid.UUID, request: UpdateQuestionRequest, author: Author
) -> QuestionResponse:
    """Retire a question so no new quiz asks it, or make it askable again.

    **Status is the only thing this changes.** A prompt, its options, its expected
    answer, its explanation, and its topics are fixed once written, because
    `quiz_attempt_answers` references the question by identifier: rewriting a
    prompt would silently rewrite the history of every attempt already marked
    against it. Correct a question by retiring it and writing another — both stay
    readable, which is the position ADR-022 takes for a superseded plan.

    **Retiring is reversible and destroys nothing.** A retired question stays in
    every quiz already assembled from it, because those quizzes have attempts
    marked against them.

    **Only the named question moves.** No quiz, no attempt, no learning stage, no
    plan, no plan item, and no revision.

    QZ-010. Serves FR-009.
    """
    try:
        question = author.update(question_id, request.to_changes())
    except QuestionNotFoundError as error:
        raise HTTPException(status_code=HTTP_404_NOT_FOUND, detail=str(error)) from error
    except EmptyQuestionUpdateError as error:
        raise _rejected("body", str(error), "empty_update") from error
    except UnknownQuestionStatusError as error:
        raise _rejected("body.status", str(error), "unknown_question_status") from error
    except AmbiguousLocalLearnerError as error:
        raise HTTPException(status_code=HTTP_409_CONFLICT, detail=str(error)) from error
    return QuestionResponse(data=QuestionSchema.of(question))
