"""Request and response schemas for the checkpoint-practice endpoints.

A separate representation from the application DTOs, so a change to the HTTP
contract does not reach back into the use case
(docs/architecture/dependency-rules.md).

Every field name is `snake_case`, per docs/api/conventions.md. No schema here
accepts a `learner_id`: the effective learner is resolved server-side.

**No response schema carries a score, a mark, a total, or a count of correct
answers.** A result is a list of per-question outcomes, and there is deliberately
nowhere to put a figure that would rate the learner
(docs/domain/terminology.md, ADR-033).

**A quiz's questions are learner-safe by shape.** `QuizQuestionSchema` has no
field for the expected answer or the explanation, so QZ-002 cannot leak an answer
by forgetting to strip one.

The length bounds below are **input guards, not stored constraints**. The columns
behind them are `text`, as docs/database/schema.md specifies for learner-facing
prose; refusing an implausible field here turns a mistake into a `422` naming the
field rather than a row nobody can read.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.application.dto.checkpoint_practice import (
    MARKABLE_QUESTION_TYPES,
    MAX_QUIZ_TOPICS,
    MAX_TOPIC_LINKS,
    QUESTION_STATUSES,
    AnswerSubmission,
    AttemptDetail,
    AttemptPage,
    NewQuestion,
    NewQuiz,
    PracticeTopic,
    QuestionChanges,
    QuestionContent,
    QuestionDetail,
    QuestionPage,
    QuizDetail,
)
from app.domain.checkpoint_marking import MAX_OPTIONS, MIN_OPTIONS
from app.presentation.api.schemas.pagination import Pagination

MAX_PROMPT_LENGTH = 4000
MAX_OPTION_LENGTH = 1000
MAX_EXPLANATION_LENGTH = 4000
MAX_ANSWERS = 200
"""How many answers one submission may carry.

A request-size guard rather than a limit on a quiz: it sits far above any quiz a
learner assembles from questions they wrote by hand.
"""


class PracticeTopicSchema(BaseModel):
    """A topic a question or a quiz covers."""

    id: uuid.UUID
    code: str | None
    name: str
    subject_id: uuid.UUID
    subject_name: str


class AnswerOptionSchema(BaseModel):
    """One option a question offers.

    `key` is assigned by LearnFlow from the option's position — the first is `a`,
    the second `b` — never accepted from a caller, so a stored expected answer
    always names an option the question offers.
    """

    key: str
    text: str


class QuestionSchema(BaseModel):
    """One practice question as its author reads it, with its expected answer."""

    id: uuid.UUID
    author_learner_id: uuid.UUID | None = Field(
        description=(
            "The learner who wrote this question. Null is reserved for curated or shared "
            "content, which nothing writes today."
        )
    )
    question_type: str = Field(description=f"One of: {', '.join(MARKABLE_QUESTION_TYPES)}.")
    source_type: str = Field(
        description=(
            "Always `curated`: the learner wrote it. Nothing here is generated by a model or "
            "taken from a previous-year paper."
        )
    )
    prompt: str
    options: list[AnswerOptionSchema]
    expected_option_key: str = Field(description="The key of the option marked correct.")
    explanation: str | None = Field(
        description="Why that answer is the expected one, shown after an attempt is marked."
    )
    status: str = Field(
        description=(
            f"One of: {', '.join(QUESTION_STATUSES)}. `retired` sets a question aside so no "
            "new quiz asks it, and it is reversible — nothing deletes a question."
        )
    )
    written_at: datetime
    topics: list[PracticeTopicSchema] = Field(
        description="The curriculum topics this question covers. Always at least one."
    )

    @classmethod
    def of(cls, question: QuestionDetail) -> QuestionSchema:
        """Build the schema from its application DTO."""
        return cls(
            id=question.id,
            author_learner_id=question.author_learner_id,
            question_type=question.question_type,
            source_type=question.source_type,
            prompt=question.prompt,
            options=[
                AnswerOptionSchema(key=option.key, text=option.text) for option in question.options
            ],
            expected_option_key=question.expected_option_key,
            explanation=question.explanation,
            status=question.status,
            written_at=question.written_at,
            topics=[_topic(topic) for topic in question.topics],
        )


class QuestionResponse(BaseModel):
    """One practice question, under the documented `data` envelope."""

    data: QuestionSchema


class QuestionCollectionResponse(BaseModel):
    """A page of practice questions, with the documented pagination block."""

    data: list[QuestionSchema]
    pagination: Pagination

    @classmethod
    def of(cls, page: QuestionPage, *, limit: int, offset: int) -> QuestionCollectionResponse:
        """Build the response from the application's page."""
        return cls(
            data=[QuestionSchema.of(question) for question in page.questions],
            pagination=Pagination(limit=limit, offset=offset, total=page.total),
        )


class WriteQuestionRequest(BaseModel):
    """What QZ-008 asks: one practice question the learner has written.

    An unknown field is rejected rather than ignored. There is deliberately no
    `status`, no `source_type`, and no `question_type`: a question is written
    `ready`, `curated`, and multiple-choice, and setting it aside is a later
    statement made through QZ-010.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    prompt: str = Field(
        min_length=1,
        max_length=MAX_PROMPT_LENGTH,
        description="The question, in your own words.",
    )
    options: list[str] = Field(
        min_length=MIN_OPTIONS,
        max_length=MAX_OPTIONS,
        description=(
            f"The options offered, {MIN_OPTIONS} to {MAX_OPTIONS} of them, in order. Keys are "
            "assigned by position: the first is `a`, the second `b`."
        ),
    )
    correct_option_index: int = Field(
        ge=0,
        lt=MAX_OPTIONS,
        description="Which option is the expected answer, counted from zero.",
    )
    explanation: str | None = Field(
        default=None,
        max_length=MAX_EXPLANATION_LENGTH,
        description="Why that answer is the expected one. Shown after an attempt is marked.",
    )
    topic_ids: list[uuid.UUID] = Field(
        min_length=1,
        max_length=MAX_TOPIC_LINKS,
        description=(
            "The topics this question covers. At least one is required, because a quiz is "
            "assembled by topic and a question covering none could never be asked."
        ),
    )

    def to_new_question(self) -> NewQuestion:
        """Map the request onto its application DTO."""
        return NewQuestion(
            prompt=self.prompt,
            option_texts=tuple(self.options),
            correct_option_index=self.correct_option_index,
            explanation=self.explanation,
            topic_ids=tuple(self.topic_ids),
        )


class UpdateQuestionRequest(BaseModel):
    """A change to a practice question (QZ-010).

    Either or both of a `status` and the question's content. An empty body is
    refused: a request naming nothing to change has misread the contract.

    **The content fields travel as one group** — `prompt`, `options`,
    `correct_option_index`, and `topic_ids` are supplied together or not at all,
    because option keys are assigned by position and the expected answer is an
    index into the options, so one without the others could not be interpreted.
    An `explanation` left out of a supplied group is **cleared**, which is the
    group-replacement rule ADR-019 fixed for planning preferences.

    **Content may be rewritten only while no quiz has asked the question**, and
    only while it is `ready`. Once a quiz has asked it, `quiz_attempt_answers`
    references it by identifier and a stored `is_correct` was decided against the
    wording as it then stood, so rewriting it would change what a past result
    says; the learner sets it aside and writes another instead. See ADR-033,
    narrowed by ADR-035.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    status: str | None = Field(
        default=None,
        description=(
            f"One of: {', '.join(QUESTION_STATUSES)}. Retiring is reversible and destroys nothing."
        ),
    )
    prompt: str | None = Field(
        default=None,
        min_length=1,
        max_length=MAX_PROMPT_LENGTH,
        description="The corrected question, in your own words.",
    )
    options: list[str] | None = Field(
        default=None,
        min_length=MIN_OPTIONS,
        max_length=MAX_OPTIONS,
        description=(
            f"The options now offered, {MIN_OPTIONS} to {MAX_OPTIONS} of them, in order. Keys are "
            "reassigned by position: the first is `a`, the second `b`."
        ),
    )
    correct_option_index: int | None = Field(
        default=None,
        ge=0,
        lt=MAX_OPTIONS,
        description="Which option is now the expected answer, counted from zero.",
    )
    explanation: str | None = Field(
        default=None,
        max_length=MAX_EXPLANATION_LENGTH,
        description=(
            "Why that answer is the expected one. Left out of a supplied content group, it is "
            "cleared."
        ),
    )
    topic_ids: list[uuid.UUID] | None = Field(
        default=None,
        min_length=1,
        max_length=MAX_TOPIC_LINKS,
        description="The topics this question now covers, replacing the ones it named.",
    )

    @model_validator(mode="after")
    def _content_travels_together(self) -> UpdateQuestionRequest:
        """Refuse a content group that is only partly supplied.

        Rejected rather than filled in from what is stored: an expected answer is
        an index into the options of *this* request, so pairing it with options
        the caller did not send would mark a different answer as expected.
        """
        supplied = {
            "prompt": self.prompt is not None,
            "options": self.options is not None,
            "correct_option_index": self.correct_option_index is not None,
            "topic_ids": self.topic_ids is not None,
        }
        if any(supplied.values()) and not all(supplied.values()):
            missing = ", ".join(name for name, given in supplied.items() if not given)
            raise ValueError(
                "A question's content is corrected as a whole, so prompt, options, "
                f"correct_option_index, and topic_ids travel together. Missing: {missing}."
            )
        if self.explanation is not None and not any(supplied.values()):
            raise ValueError(
                "An explanation is part of the question's content, so it is sent with the "
                "prompt, options, correct_option_index, and topic_ids."
            )
        return self

    def to_changes(self) -> QuestionChanges:
        """Map the request onto the application's partial-update structure."""
        content = None
        if self.prompt is not None:
            content = QuestionContent(
                prompt=self.prompt,
                option_texts=tuple(self.options or ()),
                correct_option_index=self.correct_option_index or 0,
                explanation=self.explanation,
                topic_ids=tuple(self.topic_ids or ()),
            )
        return QuestionChanges(status=self.status, content=content)


class QuizQuestionSchema(BaseModel):
    """One question as a quiz asks it.

    **Learner-safe by shape.** There is no field for the expected answer and none
    for the explanation, so neither can reach the browser before the learner has
    answered. That is what QZ-002 means by "quiz content without expected
    answers".
    """

    position: int = Field(
        description="Where the question falls in the quiz. An order, never a score."
    )
    question_id: uuid.UUID
    prompt: str
    options: list[AnswerOptionSchema]


class QuizSchema(BaseModel):
    """One checkpoint quiz as a learner reads it."""

    id: uuid.UUID
    learner_id: uuid.UUID | None
    title: str = Field(
        description="Composed by LearnFlow from the topics the quiz covers, not asked of you."
    )
    source_type: str = Field(
        description="Always `curated`: assembled from questions the learner wrote."
    )
    status: str
    topics: list[PracticeTopicSchema] = Field(
        description="The curriculum topics this quiz covers. Always at least one."
    )
    questions: list[QuizQuestionSchema] = Field(
        description=(
            "Every ready question you wrote for those topics, in the order you wrote them. "
            "LearnFlow selects none and leaves none out."
        )
    )

    @classmethod
    def of(cls, quiz: QuizDetail) -> QuizSchema:
        """Build the schema from its application DTO."""
        return cls(
            id=quiz.id,
            learner_id=quiz.learner_id,
            title=quiz.title,
            source_type=quiz.source_type,
            status=quiz.status,
            topics=[_topic(topic) for topic in quiz.topics],
            questions=[
                QuizQuestionSchema(
                    position=question.position,
                    question_id=question.question_id,
                    prompt=question.prompt,
                    options=[
                        AnswerOptionSchema(key=option.key, text=option.text)
                        for option in question.options
                    ],
                )
                for question in quiz.questions
            ],
        )


class QuizResponse(BaseModel):
    """One checkpoint quiz, under the documented `data` envelope."""

    data: QuizSchema


class AssembleQuizRequest(BaseModel):
    """What QZ-001 asks: the topics to practise.

    ADR-008's rule is enforced here as well as in the use case: a request naming
    no topic is rejected rather than stored.
    """

    model_config = ConfigDict(extra="forbid")

    topic_ids: list[uuid.UUID] = Field(
        min_length=1,
        max_length=MAX_QUIZ_TOPICS,
        description=(
            "The topics to draw questions from. At least one is required. Every ready "
            "question you wrote for them is asked."
        ),
    )

    def to_new_quiz(self) -> NewQuiz:
        """Map the request onto its application DTO."""
        return NewQuiz(topic_ids=tuple(self.topic_ids))


class AttemptOutcomeSchema(BaseModel):
    """What became of one question in one attempt.

    `expected_option_key` and `explanation` are null until the attempt has been
    marked, so opening a result early reveals nothing.

    **There is no mark and no marks available.** `is_correct` is the whole
    outcome, and it is null for a question the learner left alone — an unanswered
    question is not a wrong one.
    """

    position: int
    question_id: uuid.UUID
    prompt: str
    options: list[AnswerOptionSchema]
    chosen_option_key: str | None = Field(
        description="The option the learner chose, or null if they answered nothing."
    )
    expected_option_key: str | None = Field(
        description="The expected option, once the attempt has been marked."
    )
    explanation: str | None = Field(
        description="Why that answer is the expected one, once the attempt has been marked."
    )
    is_correct: bool | None = Field(
        description=(
            "Whether the chosen option matches the expected one. Null when the question was "
            "left unanswered, which is not the same as answering it wrongly."
        )
    )


class AttemptSchema(BaseModel):
    """One attempt as a learner reads it.

    **Nothing here totals the outcomes.** There is no score, no count of correct
    answers, and no percentage: a learner reads what happened question by
    question. See docs/domain/terminology.md and ADR-033.
    """

    id: uuid.UUID
    learner_id: uuid.UUID
    checkpoint_quiz_id: uuid.UUID
    quiz_title: str
    status: str = Field(
        description="`in_progress` until it is submitted, then `evaluated`. Marking is immediate."
    )
    started_at: datetime | None
    submitted_at: datetime | None
    evaluated_at: datetime | None
    topics: list[PracticeTopicSchema]
    outcomes: list[AttemptOutcomeSchema] = Field(
        description=(
            "Every question of the quiz, in the order it asks them, whether or not it was answered."
        )
    )

    @classmethod
    def of(cls, attempt: AttemptDetail) -> AttemptSchema:
        """Build the schema from its application DTO."""
        return cls(
            id=attempt.id,
            learner_id=attempt.learner_id,
            checkpoint_quiz_id=attempt.checkpoint_quiz_id,
            quiz_title=attempt.quiz_title,
            status=attempt.status,
            started_at=attempt.started_at,
            submitted_at=attempt.submitted_at,
            evaluated_at=attempt.evaluated_at,
            topics=[_topic(topic) for topic in attempt.topics],
            outcomes=[
                AttemptOutcomeSchema(
                    position=outcome.position,
                    question_id=outcome.question_id,
                    prompt=outcome.prompt,
                    options=[
                        AnswerOptionSchema(key=option.key, text=option.text)
                        for option in outcome.options
                    ],
                    chosen_option_key=outcome.chosen_option_key,
                    expected_option_key=outcome.expected_option_key,
                    explanation=outcome.explanation,
                    is_correct=outcome.is_correct,
                )
                for outcome in attempt.outcomes
            ],
        )


class AttemptResponse(BaseModel):
    """One attempt, under the documented `data` envelope."""

    data: AttemptSchema


class AttemptCollectionResponse(BaseModel):
    """A page of attempts, with the documented pagination block."""

    data: list[AttemptSchema]
    pagination: Pagination

    @classmethod
    def of(cls, page: AttemptPage, *, limit: int, offset: int) -> AttemptCollectionResponse:
        """Build the response from the application's page."""
        return cls(
            data=[AttemptSchema.of(attempt) for attempt in page.attempts],
            pagination=Pagination(limit=limit, offset=offset, total=page.total),
        )


class SubmittedAnswerSchema(BaseModel):
    """One answer a learner is submitting."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    question_id: uuid.UUID
    option_key: str = Field(min_length=1, description="The key of the option chosen.")


class SubmitAttemptRequest(BaseModel):
    """What QZ-005 asks: every answer, in one submission.

    **The whole attempt is submitted at once.** QZ-004, which saves one answer
    before submission, is deliberately not implemented: a single submission is one
    form post that works with no JavaScript. See ADR-033.

    A question the learner left alone is **absent** from `answers` rather than
    sent with a null. It is recorded as unanswered, never as wrong.
    """

    model_config = ConfigDict(extra="forbid")

    answers: list[SubmittedAnswerSchema] = Field(
        default_factory=list,
        max_length=MAX_ANSWERS,
        description=(
            "The answers chosen. Omit a question to leave it unanswered; an empty list "
            "submits an attempt with nothing answered, which is allowed."
        ),
    )

    def to_submissions(self) -> tuple[AnswerSubmission, ...]:
        """Map the request onto its application DTOs."""
        return tuple(
            AnswerSubmission(question_id=answer.question_id, option_key=answer.option_key)
            for answer in self.answers
        )


def _topic(topic: PracticeTopic) -> PracticeTopicSchema:
    """Map a `PracticeTopic` onto its schema.

    Written once rather than three times, because a topic reads the same way on a
    question, a quiz, and an attempt.
    """
    return PracticeTopicSchema.model_validate(topic, from_attributes=True)
